### PR TITLE
Merge blockcore and resolve conflicts 

### PR DESCRIPTION
**Pull request by dangershony**
This merge brings all the latest change form blockcore (also upgrading to dotnet core 2.2)

### CODE REVIEW

**Comment by aubergemediale** [comment]
awesome!

**Comment by dangershony** [comment]
Successfully synced ODX network from a clean folder (apart for wallets)

**Comment by dangershony** [comment]
This also contains the wallet method GetNewAddress needed to list with Solaris exchange

**Comment by aubergemediale** [comment]
sounds good...well this needs to be done, so let's do this now. Commit it when you think, and when we see bugs we'll just fix them. The fixes (if any a necessary) would be relatively small changes, compared to the whole sync.

**Pull request merged**
