### PR TITLE
Adjust fees and allowed tx size

### PR DESCRIPTION
**Pull request by aubergemediale**

### CODE REVIEW

**Comment by aubergemediale** [comment]
- fee of 0.001/1000 bytes -> max fee for a block = 1 ODX, which seems also legit given that the block reward is 50 ODX or 20 ODX later. Fees are really the only spam protection.
- size: large tx not going through has been a hazzle in the past, especially for exchanges. When users withdraw, withdrawals from exchange wallets start to fail, and the a ticket must be opened. Then, some personal starts to defragment the wallet to make the withdrawal in one tx for the user possible. Same applies to users which have for some reason many utxos in teh wallet and wnat to send a larger amount.

**Comment by aubergemediale** [comment]
- with the above being said, I this it can still be done better. The fee rate could still be _significantly_ higher, and I think we should think about the fee in terms of fiat, not sats. If a simple tx costs a cent, I think that's not too expensive.
- What about a dynamic tx size limit:
-- if the previous block was empty, or not over 10% filled, we could skip the tx size limit at all, so that only the block size limit is the barrier.
--- perhaps the mempool could subscribe to the BlockConnected signal, and always keep the last block in a field where it can look quickly at it's size.

One thing that's imo missing altogether is a special ~~fee~~ MinRequiredBurnPerKbyte for op_return outputs.
Otherwise I can do a nice app like so:
- Create a 1 MB data file and slice it into N parts, so that they fit into maxTxSize.
- Serialize that into op_return data
- Write a nice viewer/downloader app that can retrieve that data beck from the chain.
- While it's really not possible to prevent that anyway, it should at least be expensive, and the payee should be every stakeholder, not just the miners. Therefore, the cost for this should not be a fee but instead a burn of coins, e.g. 100 ODX / Mbyte.

**Comment by dangershony** [comment]
Personally I think we should not touch the fee much now (and not make it high as a mandatory requirement) because the block reward is just really high so miners have incentive to include trx regardless of the fee, later perhaps this can become an issue

**Comment by aubergemediale** [comment]
but the current fees are just bullshit numbers I entered without really thinking. So I already touched them and would like to correct my mistake, if I may :-)

**Comment by aubergemediale** [comment]
Spam is an issue and I think fee should be $0.01 or so to prevent that.

**Comment by dangershony** [comment]
Ah that's true, it is different from legacy odn already, ok so we might as well sort it out now.

**Comment by dangershony** [comment]
To clarify when I mean to not change the fees I refer to how they currently are on legacy ODN/STRAT this is probably already optimized.

**Comment by aubergemediale** [comment]
I think we can merge this one now as well...it's a reasonable step in the right direction....

**Comment by aubergemediale** [comment]
http://explorer.obsidianproject.org/fetchblock/1277
> That seems fine to me the block size is 32kb (I think the explorer measurement is incorrect it should be bytes)
> This is an ok fee

**Pull request merged**
